<html>
<head><title></title>
<link rel="stylesheet" type="text/css" href="styleastro.css"/></head>
<body><CENTER>
<h1>ASTRONOMY....(ASTRONOMY CLUB)</H1>
<H3>PURPOSE OF THE ASTRONOMY CLUB IS TO ADVANCE THE AWARENESS OF COSMOS </br>AND OPTICAL OBSERVATION OF OUTER SPACE...</BR>
</H3>
</BR></BR>

<H2><A HREF='events_astronomy.php'>VIEW EVENTS CONDUCTED BY ASTRONOMY</A></H2></BR></BR>
<H2><A HREF='schedule_astronomy.php'>VIEW SCHEDULE AND REGISTRATION_FEE OF EVENTS CONDUCTED BY ASTRONOMY</A></H2></BR></BR>
<H2><A HREF='coordinator_astronomy.php'>VIEW COORDINATOR DETAILS OF EVENTS CONDUCTED BY ASTRONOMY</A></H2></BR></BR>
<H2><A HREF='prize_astronomy.php'>VIEW PRIZE_MONEY FOR EVENTS CONDUCTED BY ASTRONOMY</A></H2></BR></BR>
</CENTER>
</BODY>
</HTML>
