<html>
<head><title></title>

<link rel="stylesheet" type="text/css" href="styleauto.css"/></head>
<body><CENTER>
<h1>AUTOMOTIVE....(AUTOMOTIVE CLUB)</H1>
<H3>THE PURPOSE IS TO NURTURE AND EXPAND KNOWLEDGE AND TO CULTIVATE INTEREST IN AUTOMOTIVE CULTURE</BR>
</H3>
</BR></BR>

<H2><A HREF='events_automotive.php'>VIEW EVENTS CONDUCTED BY AUTOMOTIVE</A></H2></BR></BR>
<H2><A HREF='schedule_automotive.php'>VIEW SCHEDULE AND REGISTRATION_FEE OF EVENTS CONDUCTED BY AUTOMOTIVE</A></H2></BR></BR>
<H2><A HREF='coordinator_automotive.php'>VIEW COORDINATOR DETAILS OF EVENTS CONDUCTED BY AUTOMOTIVE</A></H2></BR></BR>
<H2><A HREF='prize_automotive.php'>VIEW PRIZE_MONEY FOR EVENTS CONDUCTED BY AUTOMOTIVE</A></H2></BR></BR>
</CENTER>
</BODY>
</HTML>
