<html>
<head><title></title>
<link rel="stylesheet" type="text/css" href="styleavarthan.css"/></head>
<body><CENTER>
<h1>AAVARTHAN....(DANCE CLUB)</H1>
<H3>WE ARE A FAMILY,THAT IS BOUND TOGETHER BY THE THREAD OF 'LOVE FOR DANCE'.</BR>
ITS A PLACE WHERE YOU COME,DANCE,AND THEN YOU NEVER WANT TO LEAVE AGAIN.<BR/>
DANCE IS ABOUT ITS FUN,ITS FRENZY,ITS EXCITEMENT AND AAVARTHAN DANCE CLUB IS ABOUT ALL OF THE ABOVE THINGS...</BR>
</H3>
</BR></BR>

<H2><A HREF='events_avarthan.php'>VIEW EVENTS CONDUCTED BY AAVARTHAN</A></H2></BR></BR>
<H2><A HREF='schedule_avarthan.php'>VIEW SCHEDULE AND REGISTRATION_FEE OF EVENTS CONDUCTED BY AAVARTHAN</A></H2></BR></BR>
<H2><A HREF='coordinator_avarthan.php'>VIEW COORDINATOR DETAILS OF EVENTS CONDUCTED BY AAVARTHAN</A></H2></BR></BR>
<H2><A HREF='prize_avarthan.php'>VIEW PRIZE_MONEY FOR EVENTS CONDUCTED BY  AAVARTHAN</A></H2></BR></BR>
</CENTER>
</BODY>
</HTML>
