<html>
<head><title></title><link rel="stylesheet" type="text/css" href="stylejazbat.css"/>
</head>
<body><CENTER>
<h1>JAZBAAT....(DRAMATICS CLUB)</H1>
<H3> JAZBAAT..THE DRAMATICS CLUB IS ONE OF THE BIGGEST CULTURAL CLUB OF  PDPM IIITDMJ</BR>
THE CLUB HAS SHOWN ITS POTENTIAL BY WINNING AWARDS IN CULTURAL FESTS,PERFORMING ON STREETS FOR SOCIAL CAUSE ETC...</BR>
THIS GROUP INCLUDES ALL THE MEMBERS WHO HAVE EVER BEEN TO THIS CLUB..</BR>
</H3>
</BR></BR>

<H2><A HREF='events_jazbaat.php'>VIEW EVENTS CONDUCTED BY JAZBAAT</A></H2></BR></BR>
<H2><A HREF='schedule_jazbaat.php'>VIEW SCHEDULE AND REGISTRATION_FEE OF EVENTS CONDUCTED BY JAZBAAT</A></H2></BR></BR>
<H2><A HREF='coordinator_jazbaat.php'>VIEW COORDINATOR DETAILS OF EVENTS CONDUCTED BY JAZBAAT</A></H2></BR></BR>
<H2><A HREF='prize_jazbaat.php'>VIEW PRIZE_MONEY FOR EVENTS CONDUCTED BY  JAZBAAT</A></H2></BR></BR>
</CENTER>
</BODY>
</HTML>
