<html>
<head>
<link rel="stylesheet" type="text/css" href="stylelliterary.css"/>
</head>



<body><CENTER>
<h1>SAMVAAD....(LITERARY CLUB)</H1>
<H3> THA AIM OF SAMVAAD IS THE CREATION OF AN INTELLECTUAL STANDPOINT </BR>TO EXPRESS OUR BEHAVIOUR IN ALL ITS FORMS AND TO LEARN AND DEVELOP PUBLIC SPEAKING SKILLS </BR>ALONG WITH INTERPERSONAL AND IMAGE MANAGEMENT SKILLS
</H3>
</BR></BR>

<H2><A HREF='events_literary.php'>VIEW EVENTS CONDUCTED BY SAMVAAD</A></H2></BR></BR>
<H2><A HREF='schedule_literary.php'>VIEW SCHEDULE AND REGISTRATION_FEE OF EVENTS CONDUCTED BY SAMVAAD</A></H2></BR></BR>
<H2><A HREF='coordinator_literary.php'>VIEW COORDINATOR DETAILS OF EVENTS CONDUCTED BY SAMVAAD</A></H2></BR></BR>
<H2><A HREF='prize_literary.php'>VIEW PRIZE_MONEY FOR EVENTS CONDUCTED BY SAMVAAD</A></H2></BR></BR>
</CENTER>
</BODY>
</HTML>
